from pathlib import Path

APP_NAME = "Fucking Fast Downloader"
APP_VERSION = "2.0.2"
DOWNLOADS_DIR = Path.home() / "Downloads" / "Fucking Fast Downloader"
DOWNLOADS_DIR.mkdir(parents=True, exist_ok=True)

DEFAULT_TIMEOUT = 30
BETWEEN_LINK_DELAY = 1.5
STREAM_BLOCK_SIZE = 256 * 1024

HEADLESS_BROWSER = True
CF_WAIT_SECS = 120
TURNSTILE_WAIT_SECS = 25
CLICK_WIDGET_AFTER_SECS = 7
BROWSER_RESOLVE_ATTEMPTS = 4
BROWSER_RETRY_DELAY = 3.0
BROWSER_PROFILE_DIR = Path.home() / ".ff_browser_profile"

TYPICAL_PART_SIZE = 524288000
